### ISSUE TITLE
Broken imports for DatePicker and DateInput components 

### ISSUE THREAD

**Issue by riccqi** [opengovsg/design-system#59]
**Describe the bug**
On the latest 0.0.9 version, when importing DatePicker into the project, the app will crash on runtime.
DateInput component will render in, but crashes upon trying to invoke DatePicker using the icon button. Issue probably with how DatePicker is exported.
Error in the browser console as follows:
```
react-dom.development.js:28389 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ForwardRef`.
    at createFiberFromTypeAndProps (react-dom.development.js:28389:1)
    at createFiberFromElement (react-dom.development.js:28415:1)
    at reconcileSingleElement (react-dom.development.js:15620:1)
    at reconcileChildFibers (react-dom.development.js:15678:1)
    at reconcileChildren (react-dom.development.js:19964:1)
    at updateContextProvider (react-dom.development.js:21998:1)
    at beginWork (react-dom.development.js:22478:1)
    at beginWork$1 (react-dom.development.js:27381:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)
```

**To Reproduce**
1. Import DatePicker component from @opengovsg/design-system-react
2. Use the components within the react component

```
<DatePicker
    onSelectDate={function (): void {
      console.log('hello')
    }}
  />
```

3. Code compiles fine, start the app
4. App crashes on component render

**Expected behavior**
The app should not crash on render, and display the components as intended

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 103

**Additional context**
Components seem to be working fine on storybook, and only seems to break when imported in from the npm package.

**Comment by LoneRifle** [comment]
Fixed in #54
